### ISSUE TITLE
Mongo storage and image details configurable

### ISSUE THREAD

**Issue by grzegorznittner** [Ultimaker/k8s-mongo-operator#17]
First, I'd like to thank you guys for this project. I was checking kubestack, then I saw the issue you opened. I looked at this project and it looks really good. I'm going to give it a try in our setup. The project I'm working on is hosted in AWS, so some issues I may face, as I saw you use GCS.
However, I noticed that some of the stuff is hardcoded, eg:
    MONGO_IMAGE = "mongo:3.6.4"
    MONGO_NAME = "mongodb"
    MONGO_STORAGE_NAME = "mongo-storage"
    STORAGE_SIZE = "30Gi"
    STORAGE_MOUNT_PATH = "/data/db"

Opening this ticket to move those values to the custom resource definition.
Would be also great to be able to set the storage class name via custom resource definition.

**Comment by ChrisTerBeke** [comment]
That would be nice indeed. Could you make a PR to add that functionality (and maybe have some sane defaults)? I'm not sure when we have time to add this ourselves (as we focus on GCP at the moment).
