### ISSUE TITLE
Set wiredTigerCacheSizeGB

### ISSUE THREAD

**Issue by eug48** [Ultimaker/k8s-mongo-operator#22]
I'm just learning about running MongoDB in Kubernetes but it seems like `wiredTigerCacheSizeGB` should be configured according to this blog post: http://pauldone.blogspot.com/2017/06/mongodb-kubernetes-production-settings.html

Thanks for this project! I hope to have the time to evaluate it.

**Comment by ChrisTerBeke** [comment]
Thanks for bringing this up! I have added a default value that matches the default memory limit, and an optional custom resource definition parameter to override this in #24.
